# Generated by Django 5.0.4 on 2024-05-12 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reauth', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Diagnosis',
            fields=[
                ('code', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=127)),
                ('description', models.TextField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
