# Generated by Django 5.0.4 on 2024-05-30 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reauth', '0003_patientprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diagnosis',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
