# Generated by Django 5.0.4 on 2024-05-13 20:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reauth', '0003_patientprofile'),
        ('retrain', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True)),
                ('doctor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='training_temp', to='reauth.doctorprofile')),
                ('exercise', models.ManyToManyField(related_name='training_temp', to='retrain.exercises')),
            ],
        ),
    ]
