# Generated by Django 5.0.4 on 2024-05-14 09:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retrain', '0002_trainingtemplate'),
    ]

    operations = [
        migrations.CreateModel(
            name='Training',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('is_done', models.BooleanField()),
                ('training_template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training', to='retrain.trainingtemplate')),
            ],
        ),
    ]
