# Generated by Django 5.0.4 on 2024-05-14 09:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retrain', '0004_training_patient'),
    ]

    operations = [
        migrations.CreateModel(
            name='Progress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spent_time', models.TimeField()),
                ('count_repeat', models.IntegerField()),
                ('mistakes', models.IntegerField()),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='progress', to='retrain.exercises')),
                ('training', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='progress', to='retrain.training')),
            ],
        ),
    ]
